name: Build Application
run-name: ${{ github.actor }} Build with Docker Compose
on:
  push:
    paths-ignore:
      - '*.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # need checkout before using compose-action
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "docker-compose.yml"
          services: |
            database-server
            cache-server
        env:
          MYSQL_VERSION: "8.0"
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: app/package-lock.json
      - run: npm ci
        working-directory: './app'
      #- run: npm run build --if-present
      - run: npm test
        working-directory: './app'
